drop table TB_EMPP
CASCADE CONSTRAINTS;

select * from TB_EMPP;

CREATE TABLE TB_EMPP(
    ID VARCHAR2(15) NOT NULL, --아이디
    NAME VARCHAR2(20) NOT NULL, -- 이름
    PHONE VARCHAR2(20) NOT NULL, -- 전화번호
    DEPT VARCHAR2(500) NOT NULL, -- 부서
    CONSTRAINT pk_member PRIMARY KEY(id)  
)
